config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'signup' => 'users#new'
  get 'about'   => 'static_pages#about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :groceries, only: [:new, :create, :edit, :update, :destroy]
  resources :users
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
  validates :title,  presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 250 }
  validates :user_id, presence: true
  belongs_to :user
  default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 8}
  has_many :groceries, dependent: :destroy
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in"
      redirect_to login_path
    end
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :set_grocery, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :new]

  # GET /groceries/1
  # GET /groceries/1.json
  def show
  end

  # GET /groceries/new
  def new
    @grocery = Grocery.new
  end

  # GET /groceries/1/edit
  def edit
  end

  # POST /groceries
  # POST /groceries.json
  def create
    @grocery = current_user.groceries.build(grocery_params)
      if @grocery.save
        redirect_to root_url
      else
        render "new"
      end
   end

  # PATCH/PUT /groceries/1
  # PATCH/PUT /groceries/1.json
  def update
    if @grocery.update(grocery_params)
      redirect_to root_url
    else
      render "edit"
    end
  end

  # DELETE /groceries/1
  # DELETE /groceries/1.json
  def destroy
    @grocery.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Grocery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grocery
      @grocery = Grocery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grocery_params
      params.require(:grocery).permit(:title, :date, :description, :amount, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in? 
      redirect_to root_url
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user 
      if params[:session][:remember_me ] == "1"
        remember(user)
      else 
        forget(user)
      end  
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to '/login'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
    if current_user
      @groceries = current_user.groceries.paginate(page: params[:page], :per_page => 4)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user , only: [:show]
  before_action :correct_user, only: [:show]
  def new
    @user = User.new
    if logged_in? 
      redirect_to root_url
    end
  end

  def show
    redirect_to root_url
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
      flash.now[:success] = 'Welcome to groceries app!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "Groceries List"
    if page_title.empty?
      base_title
    else 
      page_title + " | " + base_title
    end
  end
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user) 
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
   forget(current_user)
   session.delete(:user_id)
   @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groceries/_form.html.erb
<div class="row">
  <%= form_for @grocery, :html => {:class => 'col s10 offset-s1'} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="input-field col s12">
   <%= f.label :title %><br>
   <%= f.text_field :title, class: "materialize-textarea", :placeholder => "#{@grocery.title}", :value => nil %>
 </div>
 <div class="input-field col s12">
   <%= f.label :description %><br>
   <%= f.text_area :description, class: "materialize-textarea", :placeholder => "#{@grocery.description}", :value => nil  %>
 </div>
 <div class="input-field col s12">
   <%= f.label :amount %><br>
   <%= f.number_field :amount, class: "materialize-textarea", :placeholder => "#{@grocery.amount}", :min => "0"  %>
 </div>
 <div class="input-field col s12">
   <%= f.label :price %><br>
   <%= f.number_field :price, class: "materialize-textarea", :placeholder => "#{@grocery.price}", :min => "0"  %>
 </div>
  <div class="col s12">
     <div class="actions">
    <%= f.submit 'Submit', :class => 'btn waves-effect waves-light btn-blue btn-grocery-submit' %>
  </div>
</div>


</div>
<% end %>

app/views/groceries/_grocery.html.erb
<li class="collection-item" id="grocery-<%= grocery.id %>">
  <div class="collapsible-header">
    <div class="row">
      <div class="col s8">
        <p class="grocery-title">
          <%= grocery.title %>
        </p>
      </div><!--col -->
      <div class="col s2">
       <input type="checkbox" class="checkbox">
     </div>
      <div class="col s2 right-align">
        <a class="dropdown-button" href="#!" data-activates="dropdown<%= grocery.id %>"><i class="fa fa-ellipsis-v fa-dropdown"></i></a>
      </div><!--col -->
    </div><!--row-->
  </div><!--header -->
  <div class="collapsible-body">
    <div class="row collapsible-row">
      <div class="col s8">
        <p class="grocery-description">
          <%= grocery.description %>
        </p>
      </div><!--col-->
      
      <div class="col s4">
        <p class="grocery-info">Amount: <%= grocery.amount %></p>
        
        <p class="grocery-info">Price: <%= grocery.price %>$</p>
      </div>
    </div><!--row-->
  </div><!--body-->
</li>

<ul id="dropdown<%= grocery.id %>" class="dropdown-content">
  <li class="dropdown-item">
   <%= link_to "Edit", edit_grocery_path(grocery) %>
 </li>
 <li class="dropdown-item">
   <%= link_to "Delete", grocery, method: :delete, data: {confirm: "Are you sure?"}%>

 </li>
</ul>
<script>
 $(document).ready(function(){
  $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });

  
});
</script>

app/views/groceries/edit.html.erb
<% provide(:title, "Edit") %>
<div class="row grocery-row">
  <h1 class="grocery-edit animated pulse">Edit Grocery</h1>
  <div class="col s8 offset-s2">
    
    <%= render 'form' %>
  </div>
</div>

app/views/groceries/index.html.erb
<% provide(:title, "Your Groceries") %>
<p id="notice"><%= notice %></p>

<h1>Your Groceries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groceries.each do |grocery| %>
      <tr>
        <td><%= grocery.title %></td>
        <td><%= grocery.description %></td>
        <td><%= link_to 'Show', grocery %></td>
        <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
        <td><%= link_to 'Destroy', grocery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grocery', new_grocery_path %>

app/views/groceries/new.html.erb
<% provide(:title, "New") %>
<div class="row grocery-row">
  <div class="col s8 offset-s2">
    <h1 class="grocery-new animated pulse">New Grocery</h1>
    <%= render 'form' %>
  </div>
  
</div>

app/views/groceries/show.html.erb
<% provide(:title, "Show") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @grocery.title %>
</p>


<p>
  <strong>Description:</strong>
  <%= @grocery.description %>
</p>

<%= link_to 'Edit', edit_grocery_path(@grocery) %> |
<%= link_to 'Back', groceries_path %>

app/views/layouts/_header.html.erb
 <nav class="navbar">
  <div class="nav-wrapper">
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <% if logged_in? %>
    <ul class="left hide-on-med-and-down navbar-list">
      <li>
       <%= link_to root_path do %>
        <i class="fa fa-home"></i>
       <% end%>
      </li> 
    </ul>
    <ul class="right hide-on-med-and-down navbar-list">
      <li>
        <%= link_to new_grocery_path do %>
        <i class="fa fa-plus"></i>
        <% end%>
      </li>
      <li>
        <%= link_to logout_path, method: :delete  do%>
        <i class="fa fa-sign-out"></i>
        <% end%>
      </li>
    <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
  <ul class="side-nav" id="mobile-demo">
   <% if logged_in? %>
   <li><%= link_to "Home",   root_path %></li>
   <li><%= link_to "Create Grocery", new_grocery_path%></li>
   <li><%= link_to "Log out", logout_path, method: :delete %></li>
   <% else %>
   <li><%= link_to "Log in", login_path %></li>
   <% end %>
 </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="icon" type="image/png" href="favicon.png" />
</head>
<body>
  <div class="row main-row">
    <% if logged_in? %>
     <%= render 'layouts/header' %>
    <% end %>
    <div class="col s6 offset-s3 flash-col">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <p class="flash-paragraph"><%= message %></p>
        </div>
      <% end %>
    </div>
   <%= yield %>
   <div class="footer">
     <div class="col s6 offset-s3">
     <span class="footer-heading">Made with <i class="fa fa-heart animated pulse"></i> by <a href="https://twitter.com/tonkec_palonkec" target="_blank">@tonkec</a></span>
     </div>
   </div>
 </div>


 <script>
   $(".button-collapse").sideNav();
 </script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="col s8 offset-s2 error_explanation">
<h2>Ouch!</h2>
  <ul class="error-list">
    <% object.errors.full_messages.each do |message| %>
    <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_form.html.erb
<div class="row">
  <%= form_for @user, :html => {:class => 'col s12'} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="input-field col s12">
   <%= f.label :name %><br>
   <%= f.text_field :name, class: "materialize-textarea" %>
 </div>
 <div class="input-field col s12">
   <%= f.label :email %><br>
   <%= f.text_field :email, class: "materialize-textarea" %>
 </div>
 <div class="input-field col s12">
   <%= f.label :password %><br>
   <%= f.password_field :password, class: "materialize-textarea" %>
 </div>
 <div class="input-field col s12">
   <%= f.label :password_confirmation %><br>
   <%= f.password_field :password_confirmation, class: "materialize-textarea" %>
 </div>
 <div class="col s12 actions">
  <%= f.submit 'Submit', :class => 'btn waves-effect waves-light btn-blue' %>
</div>


</div>
<% end %>

app/views/shared/_user.html.erb
<div class="row users-main-row">
  <div class="row users-row">
    <div class="col s10 offset-s1 m8 offset-m2 l6 offset-l3">
      <p id="notice"><%= notice %></p>
      <% if current_user.groceries.any? %>
      <h1 class="grocery-heading animated pulse">Your current groceries</h1>
    </div>
  </div>
  <div class="row groceries-list">
    <div class="col s10 offset-s1 m8 offset-m2 l6 offset-l3">
      <ul class="collapsible popout collapsible-accordion">
        <%= render @groceries %>      
      </ul>
      <%= will_paginate @groceries, :page_links => false, :html => false %>
      <% else %>
      <h1 class="grocery-heading animated pulse">You don't have groceries yet!</h1>
      <% end %>
    </div>
  </div>  
</div>

<script>
  $(document).ready(function(){
    $(".dropdown-button").dropdown();
    var dropdown = $(".dropdown-content");
    $(".collapsible-header").click(function(){
      if ($(dropdown).hasClass("active")) {
        /*alert("acitve");*/

        var collapsibleBody = $(this).siblings()
        $(collapsibleBody).css("display", "none");
      }
    });
  })
</script>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'shared/user' %>
<% else %>
<%= render template: "users/new" %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="row signup-row">
	<div class="col s12 l6">
		<h1 class="signup-title animated pulse">Sign up</h1>
		<%= render 'shared/form' %>
   <p class="signup-paragraph">Already have account? <%= link_to "Log in", login_path  %></p>
 </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Show") %>
<%= render "shared/user" %>